export enum ERole {
    ROLE_BUREAU_ETUDE = 'ROLE_BUREAU_ETUDE',
    ROLE_CONTROLEUR_TECHNIQUE = 'ROLE_CONTROLEUR_TECHNIQUE',
    ROLE_MAITRE_OUVRAGE = 'ROLE_MAITRE_OUVRAGE',
    ROLE_ENTREPRISE = 'ROLE_ENTREPRISE',
    ROLE_MAITRE_OEUVRE = 'ROLE_MAITRE_OEUVRE',
    ROLE_SOUS_TRAITANT = 'ROLE_SOUS_TRAITANT',
    ROLE_ADMIN = 'ROLE_ADMIN'
} 